// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"unicode/utf8"
	"golang.org/x/text/encoding/charmap"
)


/**
 * Test files for APNG can be found at the following locations:
 * 
 *   * <https://philip.html5.org/tests/apng/tests.html>
 *   * <http://littlesvr.ca/apng/>
 */

type Png_BlendOpValues int
const (
	Png_BlendOpValues__Source Png_BlendOpValues = 0
	Png_BlendOpValues__Over Png_BlendOpValues = 1
)
var values_Png_BlendOpValues = map[Png_BlendOpValues]struct{}{0: {}, 1: {}}
func (v Png_BlendOpValues) isDefined() bool {
	_, ok := values_Png_BlendOpValues[v]
	return ok
}

type Png_ColorType int
const (
	Png_ColorType__Greyscale Png_ColorType = 0
	Png_ColorType__Truecolor Png_ColorType = 2
	Png_ColorType__Indexed Png_ColorType = 3
	Png_ColorType__GreyscaleAlpha Png_ColorType = 4
	Png_ColorType__TruecolorAlpha Png_ColorType = 6
)
var values_Png_ColorType = map[Png_ColorType]struct{}{0: {}, 2: {}, 3: {}, 4: {}, 6: {}}
func (v Png_ColorType) isDefined() bool {
	_, ok := values_Png_ColorType[v]
	return ok
}

type Png_CompressionMethods int
const (
	Png_CompressionMethods__Zlib Png_CompressionMethods = 0
)
var values_Png_CompressionMethods = map[Png_CompressionMethods]struct{}{0: {}}
func (v Png_CompressionMethods) isDefined() bool {
	_, ok := values_Png_CompressionMethods[v]
	return ok
}

type Png_DisposeOpValues int
const (
	Png_DisposeOpValues__None Png_DisposeOpValues = 0
	Png_DisposeOpValues__Background Png_DisposeOpValues = 1
	Png_DisposeOpValues__Previous Png_DisposeOpValues = 2
)
var values_Png_DisposeOpValues = map[Png_DisposeOpValues]struct{}{0: {}, 1: {}, 2: {}}
func (v Png_DisposeOpValues) isDefined() bool {
	_, ok := values_Png_DisposeOpValues[v]
	return ok
}

type Png_FilterMethod int
const (
	Png_FilterMethod__Base Png_FilterMethod = 0
)
var values_Png_FilterMethod = map[Png_FilterMethod]struct{}{0: {}}
func (v Png_FilterMethod) isDefined() bool {
	_, ok := values_Png_FilterMethod[v]
	return ok
}

type Png_InterlaceMethod int
const (
	Png_InterlaceMethod__None Png_InterlaceMethod = 0
	Png_InterlaceMethod__Adam7 Png_InterlaceMethod = 1
)
var values_Png_InterlaceMethod = map[Png_InterlaceMethod]struct{}{0: {}, 1: {}}
func (v Png_InterlaceMethod) isDefined() bool {
	_, ok := values_Png_InterlaceMethod[v]
	return ok
}

type Png_PhysUnit int
const (
	Png_PhysUnit__Unknown Png_PhysUnit = 0
	Png_PhysUnit__Meter Png_PhysUnit = 1
)
var values_Png_PhysUnit = map[Png_PhysUnit]struct{}{0: {}, 1: {}}
func (v Png_PhysUnit) isDefined() bool {
	_, ok := values_Png_PhysUnit[v]
	return ok
}
type Png struct {
	Magic []byte
	IhdrLen uint32
	IhdrType []byte
	Ihdr *Png_IhdrChunk
	IhdrCrc uint32
	Chunks []*Png_Chunk
	_io *kaitai.Stream
	_root *Png
	_parent kaitai.Struct
}
func NewPng() *Png {
	return &Png{
	}
}

func (this Png) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png) Read(io *kaitai.Stream, parent kaitai.Struct, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Magic = tmp1
	if !(bytes.Equal(this.Magic, []uint8{137, 80, 78, 71, 13, 10, 26, 10})) {
		return kaitai.NewValidationNotEqualError([]uint8{137, 80, 78, 71, 13, 10, 26, 10}, this.Magic, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IhdrLen = uint32(tmp2)
	if !(this.IhdrLen == 13) {
		return kaitai.NewValidationNotEqualError(13, this.IhdrLen, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this.IhdrType = tmp3
	if !(bytes.Equal(this.IhdrType, []uint8{73, 72, 68, 82})) {
		return kaitai.NewValidationNotEqualError([]uint8{73, 72, 68, 82}, this.IhdrType, this._io, "/seq/2")
	}
	tmp4 := NewPng_IhdrChunk()
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Ihdr = tmp4
	tmp5, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.IhdrCrc = uint32(tmp5)
	for i := 1;; i++ {
		tmp6 := NewPng_Chunk()
		err = tmp6.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp6
		this.Chunks = append(this.Chunks, _it)
		tmp7, err := _it.Type()
		if err != nil {
			return err
		}
		tmp8, err := this._io.EOF()
		if err != nil {
			return err
		}
		if  ((tmp7 == "IEND") || (tmp8))  {
			break
		}
	}
	return err
}

/**
 * @see <a href="https://stackoverflow.com/questions/4242402/the-fireworks-png-format-any-insight-any-libs/51683285#51683285">Source</a>
 */
type Png_AdobeFireworksChunk struct {
	PreviewData []byte
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_raw_PreviewData []byte
}
func NewPng_AdobeFireworksChunk() *Png_AdobeFireworksChunk {
	return &Png_AdobeFireworksChunk{
	}
}

func (this Png_AdobeFireworksChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_AdobeFireworksChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this._raw_PreviewData = tmp9
	tmp10, err := kaitai.ProcessZlib(this._raw_PreviewData)
	if err != nil {
		return err
	}
	this.PreviewData = tmp10
	return err
}

/**
 * @see <a href="https://www.w3.org/TR/png/#acTL-chunk">Source</a>
 */
type Png_AnimationControlChunk struct {
	NumFrames uint32
	NumPlays uint32
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_AnimationControlChunk() *Png_AnimationControlChunk {
	return &Png_AnimationControlChunk{
	}
}

func (this Png_AnimationControlChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_AnimationControlChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp11, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NumFrames = uint32(tmp11)
	tmp12, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.NumPlays = uint32(tmp12)
	return err
}

/**
 * Number of frames, must be equal to the number of `fcTL` chunks (i.e.
 * `frame_control_chunk` objects)
 */

/**
 * Number of times to loop, 0 indicates infinite looping.
 */

/**
 * @see <a href="https://github.com/skeeto/scratch/tree/58470254f4a95cdf7a53888e405c851c21eb2cae/pngattach">Source</a>
 * @see <a href="https://nullprogram.com/blog/2021/12/31/">A new protocol and tool for PNG file attachments</a>
 */

type Png_AtchChunk_CompressionAttachMethods int
const (
	Png_AtchChunk_CompressionAttachMethods__None Png_AtchChunk_CompressionAttachMethods = 0
	Png_AtchChunk_CompressionAttachMethods__Zlib Png_AtchChunk_CompressionAttachMethods = 1
)
var values_Png_AtchChunk_CompressionAttachMethods = map[Png_AtchChunk_CompressionAttachMethods]struct{}{0: {}, 1: {}}
func (v Png_AtchChunk_CompressionAttachMethods) isDefined() bool {
	_, ok := values_Png_AtchChunk_CompressionAttachMethods[v]
	return ok
}
type Png_AtchChunk struct {
	FileName string
	Compression Png_AtchChunk_CompressionAttachMethods
	DataPlain []byte
	DataZlib []byte
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_raw_DataZlib []byte
	_f_data bool
	data []byte
}
func NewPng_AtchChunk() *Png_AtchChunk {
	return &Png_AtchChunk{
	}
}

func (this Png_AtchChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_AtchChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp13, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	this.FileName = string(tmp13)
	{
		_it := this.FileName
		if !( ((utf8.RuneCountInString(_it) != 0) && (_it[0:1] != ".")) ) {
			return kaitai.NewValidationExprError(this.FileName, this._io, "/types/atch_chunk/seq/0")
		}
	}
	tmp14, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Compression = Png_AtchChunk_CompressionAttachMethods(tmp14)
	if !this.Compression.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.Compression, this._io, "/types/atch_chunk/seq/1")
	}
	if (this.Compression == Png_AtchChunk_CompressionAttachMethods__None) {
		tmp15, err := this._io.ReadBytesFull()
		if err != nil {
			return err
		}
		tmp15 = tmp15
		this.DataPlain = tmp15
	}
	if (this.Compression == Png_AtchChunk_CompressionAttachMethods__Zlib) {
		tmp16, err := this._io.ReadBytesFull()
		if err != nil {
			return err
		}
		tmp16 = tmp16
		this._raw_DataZlib = tmp16
		tmp17, err := kaitai.ProcessZlib(this._raw_DataZlib)
		if err != nil {
			return err
		}
		this.DataZlib = tmp17
	}
	return err
}
func (this *Png_AtchChunk) Data() (v []byte, err error) {
	if (this._f_data) {
		return this.data, nil
	}
	this._f_data = true
	var tmp18 []byte;
	if (this.Compression == Png_AtchChunk_CompressionAttachMethods__None) {
		tmp18 = this.DataPlain
	} else {
		tmp18 = this.DataZlib
	}
	this.data = []byte(tmp18)
	return this.data, nil
}

/**
 * From the [official
 * specification](https://github.com/skeeto/scratch/tree/58470254f4a95cdf7a53888e405c851c21eb2cae/pngattach#atch-chunk-specification):
 * 
 * > The name can be any length that fits in the chunk, and should be
 * > encoded with UTF-8. It's up to each implementation to determine how
 * > to appropriately interpret the bytestring for the local system.
 * 
 * > The name must be at least one byte long, not counting the null
 * > terminator. It cannot begin with a period (`0x2e`), nor contain
 * > control bytes (anything less than `0x20`), nor slash (`0x2f`), nor
 * > backslash (`0x5c`), i.e. no directory hierarchies.
 * 
 * As of Kaitai Struct 0.11, we cannot easily check whether a string
 * contains certain characters, so we only enforce that the file name is
 * not empty and that it doesn't start with a period.
 */

/**
 * Background chunk stores default background color to display this
 * image against. Contents depend on `color_type` of the image.
 * @see <a href="https://www.w3.org/TR/png/#11bKGD">Source</a>
 */
type Png_BkgdChunk struct {
	Bkgd kaitai.Struct
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_BkgdChunk() *Png_BkgdChunk {
	return &Png_BkgdChunk{
	}
}

func (this Png_BkgdChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_BkgdChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	switch (this._root.Ihdr.ColorType) {
	case Png_ColorType__Greyscale:
		tmp19 := NewPng_BkgdGreyscale()
		err = tmp19.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Bkgd = tmp19
	case Png_ColorType__GreyscaleAlpha:
		tmp20 := NewPng_BkgdGreyscale()
		err = tmp20.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Bkgd = tmp20
	case Png_ColorType__Indexed:
		tmp21 := NewPng_BkgdIndexed()
		err = tmp21.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Bkgd = tmp21
	case Png_ColorType__Truecolor:
		tmp22 := NewPng_BkgdTruecolor()
		err = tmp22.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Bkgd = tmp22
	case Png_ColorType__TruecolorAlpha:
		tmp23 := NewPng_BkgdTruecolor()
		err = tmp23.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Bkgd = tmp23
	}
	return err
}

/**
 * Background chunk for greyscale images.
 */
type Png_BkgdGreyscale struct {
	Value uint16
	_io *kaitai.Stream
	_root *Png
	_parent *Png_BkgdChunk
}
func NewPng_BkgdGreyscale() *Png_BkgdGreyscale {
	return &Png_BkgdGreyscale{
	}
}

func (this Png_BkgdGreyscale) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_BkgdGreyscale) Read(io *kaitai.Stream, parent *Png_BkgdChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Value = uint16(tmp24)
	return err
}

/**
 * Background chunk for images with indexed palette.
 */
type Png_BkgdIndexed struct {
	PaletteIndex uint8
	_io *kaitai.Stream
	_root *Png
	_parent *Png_BkgdChunk
}
func NewPng_BkgdIndexed() *Png_BkgdIndexed {
	return &Png_BkgdIndexed{
	}
}

func (this Png_BkgdIndexed) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_BkgdIndexed) Read(io *kaitai.Stream, parent *Png_BkgdChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp25, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.PaletteIndex = tmp25
	return err
}

/**
 * Background chunk for truecolor images.
 */
type Png_BkgdTruecolor struct {
	Red uint16
	Green uint16
	Blue uint16
	_io *kaitai.Stream
	_root *Png
	_parent *Png_BkgdChunk
}
func NewPng_BkgdTruecolor() *Png_BkgdTruecolor {
	return &Png_BkgdTruecolor{
	}
}

func (this Png_BkgdTruecolor) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_BkgdTruecolor) Read(io *kaitai.Stream, parent *Png_BkgdChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp26, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Red = uint16(tmp26)
	tmp27, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Green = uint16(tmp27)
	tmp28, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Blue = uint16(tmp28)
	return err
}
type Png_ChrmChromaticity struct {
	XInt uint32
	YInt uint32
	_io *kaitai.Stream
	_root *Png
	_parent *Png_ChrmChunk
	_f_x bool
	x float64
	_f_y bool
	y float64
}
func NewPng_ChrmChromaticity() *Png_ChrmChromaticity {
	return &Png_ChrmChromaticity{
	}
}

func (this Png_ChrmChromaticity) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_ChrmChromaticity) Read(io *kaitai.Stream, parent *Png_ChrmChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp29, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.XInt = uint32(tmp29)
	tmp30, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.YInt = uint32(tmp30)
	return err
}
func (this *Png_ChrmChromaticity) X() (v float64, err error) {
	if (this._f_x) {
		return this.x, nil
	}
	this._f_x = true
	this.x = float64(this.XInt / 100000.0)
	return this.x, nil
}
func (this *Png_ChrmChromaticity) Y() (v float64, err error) {
	if (this._f_y) {
		return this.y, nil
	}
	this._f_y = true
	this.y = float64(this.YInt / 100000.0)
	return this.y, nil
}

/**
 * @see <a href="https://www.w3.org/TR/png/#11cHRM">Source</a>
 */
type Png_ChrmChunk struct {
	WhitePoint *Png_ChrmChromaticity
	Red *Png_ChrmChromaticity
	Green *Png_ChrmChromaticity
	Blue *Png_ChrmChromaticity
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_ChrmChunk() *Png_ChrmChunk {
	return &Png_ChrmChunk{
	}
}

func (this Png_ChrmChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_ChrmChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp31 := NewPng_ChrmChromaticity()
	err = tmp31.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.WhitePoint = tmp31
	tmp32 := NewPng_ChrmChromaticity()
	err = tmp32.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Red = tmp32
	tmp33 := NewPng_ChrmChromaticity()
	err = tmp33.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Green = tmp33
	tmp34 := NewPng_ChrmChromaticity()
	err = tmp34.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Blue = tmp34
	return err
}
type Png_Chunk struct {
	Len uint32
	TypeRaw []byte
	Body interface{}
	Crc uint32
	_io *kaitai.Stream
	_root *Png
	_parent *Png
	_raw_Body []byte
	_f_isAncillary bool
	isAncillary bool
	_f_isPrivate bool
	isPrivate bool
	_f_isSafeToCopy bool
	isSafeToCopy bool
	_f_reservedBit bool
	reservedBit bool
	_f_type bool
	type string
}
func NewPng_Chunk() *Png_Chunk {
	return &Png_Chunk{
	}
}

func (this Png_Chunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_Chunk) Read(io *kaitai.Stream, parent *Png, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp35, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Len = uint32(tmp35)
	tmp36, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp36 = tmp36
	this.TypeRaw = tmp36
	{
		_it := this.TypeRaw
		if !( (( (( ((_it[0] >= 65) && (_it[0] <= 90)) ) || ( ((_it[0] >= 97) && (_it[0] <= 122)) )) ) && ( (( ((_it[1] >= 65) && (_it[1] <= 90)) ) || ( ((_it[1] >= 97) && (_it[1] <= 122)) )) ) && ( (( ((_it[2] >= 65) && (_it[2] <= 90)) ) || ( ((_it[2] >= 97) && (_it[2] <= 122)) )) ) && ( (( ((_it[3] >= 65) && (_it[3] <= 90)) ) || ( ((_it[3] >= 97) && (_it[3] <= 122)) )) )) ) {
			return kaitai.NewValidationExprError(this.TypeRaw, this._io, "/types/chunk/seq/1")
		}
	}
	tmp37, err := this.Type()
	if err != nil {
		return err
	}
	switch (tmp37) {
	case "PLTE":
		tmp38, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp38 = tmp38
		this._raw_Body = tmp38
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp39 := NewPng_PlteChunk()
		err = tmp39.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp39
	case "acTL":
		tmp40, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp40 = tmp40
		this._raw_Body = tmp40
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp41 := NewPng_AnimationControlChunk()
		err = tmp41.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp41
	case "atCh":
		tmp42, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp42 = tmp42
		this._raw_Body = tmp42
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp43 := NewPng_AtchChunk()
		err = tmp43.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp43
	case "bKGD":
		tmp44, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp44 = tmp44
		this._raw_Body = tmp44
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp45 := NewPng_BkgdChunk()
		err = tmp45.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp45
	case "cHRM":
		tmp46, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp46 = tmp46
		this._raw_Body = tmp46
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp47 := NewPng_ChrmChunk()
		err = tmp47.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp47
	case "cICP":
		tmp48, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp48 = tmp48
		this._raw_Body = tmp48
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp49 := NewPng_CicpChunk()
		err = tmp49.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp49
	case "cLLI":
		tmp50, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp50 = tmp50
		this._raw_Body = tmp50
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp51 := NewPng_ClliChunk()
		err = tmp51.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp51
	case "fcTL":
		tmp52, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp52 = tmp52
		this._raw_Body = tmp52
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp53 := NewPng_FrameControlChunk()
		err = tmp53.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp53
	case "fdAT":
		tmp54, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp54 = tmp54
		this._raw_Body = tmp54
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp55 := NewPng_FrameDataChunk()
		err = tmp55.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp55
	case "gAMA":
		tmp56, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp56 = tmp56
		this._raw_Body = tmp56
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp57 := NewPng_GamaChunk()
		err = tmp57.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp57
	case "iTXt":
		tmp58, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp58 = tmp58
		this._raw_Body = tmp58
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp59 := NewPng_InternationalTextChunk()
		err = tmp59.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp59
	case "mDCV":
		tmp60, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp60 = tmp60
		this._raw_Body = tmp60
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp61 := NewPng_MdcvChunk()
		err = tmp61.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp61
	case "mkBS":
		tmp62, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp62 = tmp62
		this._raw_Body = tmp62
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp63 := NewPng_AdobeFireworksChunk()
		err = tmp63.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp63
	case "mkTS":
		tmp64, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp64 = tmp64
		this._raw_Body = tmp64
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp65 := NewPng_AdobeFireworksChunk()
		err = tmp65.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp65
	case "pHYs":
		tmp66, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp66 = tmp66
		this._raw_Body = tmp66
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp67 := NewPng_PhysChunk()
		err = tmp67.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp67
	case "prVW":
		tmp68, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp68 = tmp68
		this._raw_Body = tmp68
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp69 := NewPng_AdobeFireworksChunk()
		err = tmp69.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp69
	case "sRGB":
		tmp70, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp70 = tmp70
		this._raw_Body = tmp70
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp71 := NewPng_SrgbChunk()
		err = tmp71.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp71
	case "skMf":
		tmp72, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp72 = tmp72
		this._raw_Body = tmp72
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp73 := NewPng_EvernoteSkmfChunk()
		err = tmp73.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp73
	case "skRf":
		tmp74, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp74 = tmp74
		this._raw_Body = tmp74
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp75 := NewPng_EvernoteSkrfChunk()
		err = tmp75.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp75
	case "tEXt":
		tmp76, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp76 = tmp76
		this._raw_Body = tmp76
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp77 := NewPng_TextChunk()
		err = tmp77.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp77
	case "tIME":
		tmp78, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp78 = tmp78
		this._raw_Body = tmp78
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp79 := NewPng_TimeChunk()
		err = tmp79.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp79
	case "zTXt":
		tmp80, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp80 = tmp80
		this._raw_Body = tmp80
		_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body))
		tmp81 := NewPng_CompressedTextChunk()
		err = tmp81.Read(_io__raw_Body, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp81
	default:
		tmp82, err := this._io.ReadBytes(int(this.Len))
		if err != nil {
			return err
		}
		tmp82 = tmp82
		this._raw_Body = tmp82
	}
	tmp83, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Crc = uint32(tmp83)
	return err
}

/**
 * false = critical chunk, true = ancillary chunk
 */
func (this *Png_Chunk) IsAncillary() (v bool, err error) {
	if (this._f_isAncillary) {
		return this.isAncillary, nil
	}
	this._f_isAncillary = true
	this.isAncillary = bool(this.TypeRaw[0] & 32 != 0)
	return this.isAncillary, nil
}

/**
 * false = public chunk (defined by the W3C), true = private chunk (can
 * be defined by anyone)
 */
func (this *Png_Chunk) IsPrivate() (v bool, err error) {
	if (this._f_isPrivate) {
		return this.isPrivate, nil
	}
	this._f_isPrivate = true
	this.isPrivate = bool(this.TypeRaw[1] & 32 != 0)
	return this.isPrivate, nil
}

/**
 * Defines whether the chunk may be copied if the image data (i.e.
 * pixels) is modified. This tells PNG editors how to handle unknown
 * chunks - see section [14.2 Behavior of PNG
 * editors](https://www.w3.org/TR/2025/REC-png-3-20250624/#14Ordering) in
 * the official specification.
 */
func (this *Png_Chunk) IsSafeToCopy() (v bool, err error) {
	if (this._f_isSafeToCopy) {
		return this.isSafeToCopy, nil
	}
	this._f_isSafeToCopy = true
	this.isSafeToCopy = bool(this.TypeRaw[3] & 32 != 0)
	return this.isSafeToCopy, nil
}

/**
 * Should be `false`, i.e. all chunk types should have uppercase third
 * letters (the lowercase third letter is reserved for possible future
 * extensions to the PNG standard)
 */
func (this *Png_Chunk) ReservedBit() (v bool, err error) {
	if (this._f_reservedBit) {
		return this.reservedBit, nil
	}
	this._f_reservedBit = true
	this.reservedBit = bool(this.TypeRaw[2] & 32 != 0)
	return this.reservedBit, nil
}
func (this *Png_Chunk) Type() (v string, err error) {
	if (this._f_type) {
		return this.type, nil
	}
	this._f_type = true
	this.type = string(string(this.TypeRaw))
	return this.type, nil
}

/**
 * Each byte of a chunk type is restricted to the hexadecimal values
 * 0x41..0x5a and 0x61..0x7a, i.e. uppercase and lowercase ASCII letters
 * (`A-Z` and `a-z`).
 * @see <a href="https://www.w3.org/TR/2025/REC-png-3-20250624/#table51">Source</a>
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#cICP-chunk">Source</a>
 * @see <a href="https://w3c.github.io/png/Implementation_Report_3e/#cicp">Source</a>
 */
type Png_CicpChunk struct {
	ColorPrimaries uint8
	TransferFunction uint8
	MatrixCoefficients uint8
	VideoFullRangeFlag uint8
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_CicpChunk() *Png_CicpChunk {
	return &Png_CicpChunk{
	}
}

func (this Png_CicpChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_CicpChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp84, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ColorPrimaries = tmp84
	tmp85, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TransferFunction = tmp85
	tmp86, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.MatrixCoefficients = tmp86
	if !(this.MatrixCoefficients == 0) {
		return kaitai.NewValidationNotEqualError(0, this.MatrixCoefficients, this._io, "/types/cicp_chunk/seq/2")
	}
	tmp87, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.VideoFullRangeFlag = tmp87
	if !( ((this.VideoFullRangeFlag == 0) || (this.VideoFullRangeFlag == 1)) ) {
		return kaitai.NewValidationNotAnyOfError(this.VideoFullRangeFlag, this._io, "/types/cicp_chunk/seq/3")
	}
	return err
}

/**
 * values above 22 are reserved, see
 * <https://github.com/pnggroup/pngcheck/blob/bd33ad6490269df07cac81e5305f4ebf56c2b637/pngcheck.c#L3322-L3325>
 */

/**
 * values above 18 are reserved, see
 * <https://github.com/pnggroup/pngcheck/blob/bd33ad6490269df07cac81e5305f4ebf56c2b637/pngcheck.c#L3326-L3329>
 */

/**
 * From the [official
 * specification](https://www.w3.org/TR/2025/REC-png-3-20250624/#cICP-chunk):
 * 
 * > RGB is currently the only supported color model in PNG, and as such
 * > `Matrix Coefficients` shall be set to `0`.
 */

/**
 * From the [official
 * specification](https://www.w3.org/TR/2025/REC-png-3-20250624/#cICP-chunk):
 * 
 * > If `Video Full Range Flag` value is `1`, then the image is a
 * > full-range image. Typically, images in the RGB color representation
 * > are stored in the full-range signal quantization, therefore the vast
 * > majority of computer graphics and web images, including those used
 * > in traditional PNG workflows, are full-range images.
 * 
 * > If `Video Full Range Flag` value is `0`, then the image is a
 * > narrow-range image.
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#cLLI-chunk">Source</a>
 * @see <a href="https://w3c.github.io/png/Implementation_Report_3e/#light">Source</a>
 */
type Png_ClliChunk struct {
	MaxContentLightLevelInt uint32
	MaxFrameAverageLightLevelInt uint32
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_f_maxContentLightLevel bool
	maxContentLightLevel float64
	_f_maxFrameAverageLightLevel bool
	maxFrameAverageLightLevel float64
}
func NewPng_ClliChunk() *Png_ClliChunk {
	return &Png_ClliChunk{
	}
}

func (this Png_ClliChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_ClliChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp88, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.MaxContentLightLevelInt = uint32(tmp88)
	tmp89, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.MaxFrameAverageLightLevelInt = uint32(tmp89)
	return err
}

/**
 * Maximum Content Light Level (MaxCLL), in cd/m^2
 */
func (this *Png_ClliChunk) MaxContentLightLevel() (v float64, err error) {
	if (this._f_maxContentLightLevel) {
		return this.maxContentLightLevel, nil
	}
	this._f_maxContentLightLevel = true
	this.maxContentLightLevel = float64(this.MaxContentLightLevelInt * 0.0001)
	return this.maxContentLightLevel, nil
}

/**
 * Maximum Frame Average Light Level (MaxFALL), in cd/m^2
 */
func (this *Png_ClliChunk) MaxFrameAverageLightLevel() (v float64, err error) {
	if (this._f_maxFrameAverageLightLevel) {
		return this.maxFrameAverageLightLevel, nil
	}
	this._f_maxFrameAverageLightLevel = true
	this.maxFrameAverageLightLevel = float64(this.MaxFrameAverageLightLevelInt * 0.0001)
	return this.maxFrameAverageLightLevel, nil
}
type Png_CompressedText struct {
	Value string
	_io *kaitai.Stream
	_root *Png
	_parent *Png_CompressedTextChunk
}
func NewPng_CompressedText() *Png_CompressedText {
	return &Png_CompressedText{
	}
}

func (this Png_CompressedText) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_CompressedText) Read(io *kaitai.Stream, parent *Png_CompressedTextChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp90, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp90 = tmp90
	tmp91, err := kaitai.BytesToStr(tmp90, charmap.ISO8859_1.NewDecoder())
	if err != nil {
		return err
	}
	this.Value = tmp91
	return err
}

/**
 * Text string (the "value" of this key-value pair).
 * 
 * Although it is not null-terminated (unlike the keyword), it must not
 * contain a zero byte (U+0000 NULL character). A newline should be
 * represented by a single U+000A LINE FEED (LF) character (aka `\n`).
 * The remaining control characters (U+0001..U+0009, U+000B..0+001F,
 * U+007F..U+009F) are discouraged.
 */

/**
 * Compressed textual data (`zTXt`) chunk effectively allows you to store
 * key-value string pairs in the PNG container, compressing the "value" part
 * (which can be quite lengthy) with zlib compression.
 * 
 * The `zTXt` and `tEXt` chunks are semantically equivalent, but the `zTXt`
 * chunk is recommended for storing large blocks of text.
 * @see <a href="https://www.w3.org/TR/png/#11zTXt">Source</a>
 */
type Png_CompressedTextChunk struct {
	Keyword string
	CompressionMethod Png_CompressionMethods
	Text *Png_CompressedText
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_raw_Text []byte
	_raw__raw_Text []byte
}
func NewPng_CompressedTextChunk() *Png_CompressedTextChunk {
	return &Png_CompressedTextChunk{
	}
}

func (this Png_CompressedTextChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_CompressedTextChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp92, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	tmp93, err := kaitai.BytesToStr(tmp92, charmap.ISO8859_1.NewDecoder())
	if err != nil {
		return err
	}
	this.Keyword = tmp93
	tmp94, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.CompressionMethod = Png_CompressionMethods(tmp94)
	if !(this.CompressionMethod == Png_CompressionMethods__Zlib) {
		return kaitai.NewValidationNotEqualError(Png_CompressionMethods__Zlib, this.CompressionMethod, this._io, "/types/compressed_text_chunk/seq/1")
	}
	tmp95, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp95 = tmp95
	this._raw__raw_Text = tmp95
	tmp96, err := kaitai.ProcessZlib(this._raw__raw_Text)
	if err != nil {
		return err
	}
	this._raw_Text = tmp96
	_io__raw_Text := kaitai.NewStream(bytes.NewReader(this._raw_Text))
	tmp97 := NewPng_CompressedText()
	err = tmp97.Read(_io__raw_Text, this, this._root)
	if err != nil {
		return err
	}
	this.Text = tmp97
	return err
}

/**
 * Indicates the type of information represented by the text string.
 * 
 * Keywords must consist exclusively of printable ISO-8859-1 (Latin-1)
 * characters and spaces; that is, only code points 0x20-0x7E and
 * 0xA1-0xFF are allowed. To reduce the chances for human misreading of a
 * keyword, leading spaces, trailing spaces, and consecutive spaces are
 * not permitted.
 * @see <a href="https://www.w3.org/TR/2025/REC-png-3-20250624/#11keywords">Source</a>
 */

/**
 * @see <a href="https://web.archive.org/web/20210302212148/https://discussion.evernote.com/forums/topic/88532-how-to-extract-annotation-information-from-annotated-evernoteskitch-images/#comment-451501">Source</a>
 */
type Png_EvernoteSkmfChunk struct {
	Json string
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_EvernoteSkmfChunk() *Png_EvernoteSkmfChunk {
	return &Png_EvernoteSkmfChunk{
	}
}

func (this Png_EvernoteSkmfChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_EvernoteSkmfChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp98, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp98 = tmp98
	this.Json = string(tmp98)
	return err
}

/**
 * JSON document with information about editable annotations (text,
 * lines, paths, etc.) in Evernote/Skitch.
 * 
 * It refers to the original image stored in the `skRf` chunk (which
 * usually follows immediately after `skMf`) via the
 * `.children[0].children[0].uri` JSON property. This has the format
 * `"skitch+uuid:///$UUID"`, where `$UUID` is a random UUIDv4 value that
 * matches the `uuid` field in `evernote_skrf_chunk` (i.e. in the first
 * 16 bytes of the `skRf` chunk).
 */

/**
 * @see <a href="https://web.archive.org/web/20210302212148/https://discussion.evernote.com/forums/topic/88532-how-to-extract-annotation-information-from-annotated-evernoteskitch-images/#comment-451501">Source</a>
 */
type Png_EvernoteSkrfChunk struct {
	Uuid []byte
	OrigImg []byte
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_EvernoteSkrfChunk() *Png_EvernoteSkrfChunk {
	return &Png_EvernoteSkrfChunk{
	}
}

func (this Png_EvernoteSkrfChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_EvernoteSkrfChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp99, err := this._io.ReadBytes(int(16))
	if err != nil {
		return err
	}
	tmp99 = tmp99
	this.Uuid = tmp99
	tmp100, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp100 = tmp100
	this.OrigImg = tmp100
	return err
}

/**
 * Random UUIDv4 value used to identify the image. It is referenced by
 * the `skMf` chunk - see the documentation for the `json` field in
 * `evernote_skmf_chunk`.
 */

/**
 * The original source image without annotations. It's usually a PNG
 * image as well, but it can also be a JPEG or possibly other formats.
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#fcTL-chunk">Source</a>
 */
type Png_FrameControlChunk struct {
	SequenceNumber uint32
	Width uint32
	Height uint32
	XOffset uint32
	YOffset uint32
	DelayNum uint16
	DelayDen uint16
	DisposeOp Png_DisposeOpValues
	BlendOp Png_BlendOpValues
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_f_delay bool
	delay float64
}
func NewPng_FrameControlChunk() *Png_FrameControlChunk {
	return &Png_FrameControlChunk{
	}
}

func (this Png_FrameControlChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_FrameControlChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp101, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.SequenceNumber = uint32(tmp101)
	tmp102, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Width = uint32(tmp102)
	if !(this.Width >= 1) {
		return kaitai.NewValidationLessThanError(1, this.Width, this._io, "/types/frame_control_chunk/seq/1")
	}
	if !(this.Width <= this._root.Ihdr.Width) {
		return kaitai.NewValidationGreaterThanError(this._root.Ihdr.Width, this.Width, this._io, "/types/frame_control_chunk/seq/1")
	}
	tmp103, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Height = uint32(tmp103)
	if !(this.Height >= 1) {
		return kaitai.NewValidationLessThanError(1, this.Height, this._io, "/types/frame_control_chunk/seq/2")
	}
	if !(this.Height <= this._root.Ihdr.Height) {
		return kaitai.NewValidationGreaterThanError(this._root.Ihdr.Height, this.Height, this._io, "/types/frame_control_chunk/seq/2")
	}
	tmp104, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.XOffset = uint32(tmp104)
	if !(this.XOffset <= this._root.Ihdr.Width - this.Width) {
		return kaitai.NewValidationGreaterThanError(this._root.Ihdr.Width - this.Width, this.XOffset, this._io, "/types/frame_control_chunk/seq/3")
	}
	tmp105, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.YOffset = uint32(tmp105)
	if !(this.YOffset <= this._root.Ihdr.Height - this.Height) {
		return kaitai.NewValidationGreaterThanError(this._root.Ihdr.Height - this.Height, this.YOffset, this._io, "/types/frame_control_chunk/seq/4")
	}
	tmp106, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.DelayNum = uint16(tmp106)
	tmp107, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.DelayDen = uint16(tmp107)
	tmp108, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DisposeOp = Png_DisposeOpValues(tmp108)
	if !this.DisposeOp.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.DisposeOp, this._io, "/types/frame_control_chunk/seq/7")
	}
	tmp109, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.BlendOp = Png_BlendOpValues(tmp109)
	if !this.BlendOp.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.BlendOp, this._io, "/types/frame_control_chunk/seq/8")
	}
	return err
}

/**
 * Time to display this frame, in seconds
 */
func (this *Png_FrameControlChunk) Delay() (v float64, err error) {
	if (this._f_delay) {
		return this.delay, nil
	}
	this._f_delay = true
	var tmp110 float64;
	if (this.DelayDen == 0) {
		tmp110 = 100.0
	} else {
		tmp110 = this.DelayDen
	}
	this.delay = float64(this.DelayNum / tmp110)
	return this.delay, nil
}

/**
 * Sequence number of the animation chunk, starting from 0.
 * 
 * The `fcTL` and `fdAT` chunks have a 4-byte sequence number. Both chunk
 * types share the sequence. The purpose of this number is to detect (and
 * optionally correct) sequence errors in an Animated PNG, since the PNG
 * specification does not impose ordering restrictions on ancillary
 * chunks (which means that a PNG editor is technically allowed to
 * reorder them arbitrarily, see [14.2 Behavior of PNG
 * editors](https://www.w3.org/TR/png/#14Ordering) in the spec).
 * 
 * The first `fcTL` chunk must contain sequence number 0, and the
 * sequence numbers in the remaining `fcTL` and `fdAT` chunks must be in
 * ascending order, with no gaps or duplicates.
 */

/**
 * Width of the following frame
 */

/**
 * Height of the following frame
 */

/**
 * X position at which to render the following frame
 */

/**
 * Y position at which to render the following frame
 */

/**
 * Frame delay fraction numerator
 */

/**
 * Frame delay fraction denominator
 */

/**
 * Type of frame area disposal to be done after rendering this frame
 */

/**
 * Type of frame area rendering for this frame
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#fdAT-chunk">Source</a>
 */
type Png_FrameDataChunk struct {
	SequenceNumber uint32
	FrameData []byte
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_FrameDataChunk() *Png_FrameDataChunk {
	return &Png_FrameDataChunk{
	}
}

func (this Png_FrameDataChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_FrameDataChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp111, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.SequenceNumber = uint32(tmp111)
	tmp112, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp112 = tmp112
	this.FrameData = tmp112
	return err
}

/**
 * Sequence number of the animation chunk, starting from 0.
 * 
 * The `fcTL` and `fdAT` chunks have a 4-byte sequence number. Both chunk
 * types share the sequence. The purpose of this number is to detect (and
 * optionally correct) sequence errors in an Animated PNG, since the PNG
 * specification does not impose ordering restrictions on ancillary
 * chunks (which means that a PNG editor is technically allowed to
 * reorder them arbitrarily, see [14.2 Behavior of PNG
 * editors](https://www.w3.org/TR/png/#14Ordering) in the spec).
 * 
 * The first `fcTL` chunk must contain sequence number 0, and the
 * sequence numbers in the remaining `fcTL` and `fdAT` chunks must be in
 * ascending order, with no gaps or duplicates.
 */

/**
 * Frame data for the frame. At least one `fdAT` chunk is required for
 * each frame, except for the first frame, if that frame is represented
 * by an `IDAT` chunk. The compressed datastream for each frame is the
 * concatenation of the contents of the data fields of all the `fdAT`
 * chunks within a frame.
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#11gAMA">Source</a>
 */
type Png_GamaChunk struct {
	GammaInt uint32
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_f_gamma bool
	gamma float64
	_f_invGamma bool
	invGamma float64
}
func NewPng_GamaChunk() *Png_GamaChunk {
	return &Png_GamaChunk{
	}
}

func (this Png_GamaChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_GamaChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp113, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.GammaInt = uint32(tmp113)
	{
		_it := this.GammaInt
		if !(_it != 0) {
			return kaitai.NewValidationExprError(this.GammaInt, this._io, "/types/gama_chunk/seq/0")
		}
	}
	return err
}

/**
 * Image gamma, typically 0.45455 = 1/2.2
 */
func (this *Png_GamaChunk) Gamma() (v float64, err error) {
	if (this._f_gamma) {
		return this.gamma, nil
	}
	this._f_gamma = true
	this.gamma = float64(this.GammaInt / 100000.0)
	return this.gamma, nil
}

/**
 * Inverse of the image gamma (1 / gamma), typically 2.2 (not considering
 * rounding)
 */
func (this *Png_GamaChunk) InvGamma() (v float64, err error) {
	if (this._f_invGamma) {
		return this.invGamma, nil
	}
	this._f_invGamma = true
	this.invGamma = float64(100000.0 / this.GammaInt)
	return this.invGamma, nil
}

/**
 * Image gamma multiplied by 100000 (a gamma value of 1/2.2 is stored as
 * 45455)
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#11IHDR">Source</a>
 */
type Png_IhdrChunk struct {
	Width uint32
	Height uint32
	BitDepth uint8
	ColorType Png_ColorType
	CompressionMethod Png_CompressionMethods
	FilterMethod Png_FilterMethod
	InterlaceMethod Png_InterlaceMethod
	_io *kaitai.Stream
	_root *Png
	_parent *Png
}
func NewPng_IhdrChunk() *Png_IhdrChunk {
	return &Png_IhdrChunk{
	}
}

func (this Png_IhdrChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_IhdrChunk) Read(io *kaitai.Stream, parent *Png, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp114, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Width = uint32(tmp114)
	if !(this.Width >= 1) {
		return kaitai.NewValidationLessThanError(1, this.Width, this._io, "/types/ihdr_chunk/seq/0")
	}
	tmp115, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Height = uint32(tmp115)
	if !(this.Height >= 1) {
		return kaitai.NewValidationLessThanError(1, this.Height, this._io, "/types/ihdr_chunk/seq/1")
	}
	tmp116, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.BitDepth = tmp116
	if !( ((this.BitDepth == 1) || (this.BitDepth == 2) || (this.BitDepth == 4) || (this.BitDepth == 8) || (this.BitDepth == 16)) ) {
		return kaitai.NewValidationNotAnyOfError(this.BitDepth, this._io, "/types/ihdr_chunk/seq/2")
	}
	tmp117, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.ColorType = Png_ColorType(tmp117)
	if !this.ColorType.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.ColorType, this._io, "/types/ihdr_chunk/seq/3")
	}
	tmp118, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.CompressionMethod = Png_CompressionMethods(tmp118)
	if !this.CompressionMethod.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.CompressionMethod, this._io, "/types/ihdr_chunk/seq/4")
	}
	tmp119, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.FilterMethod = Png_FilterMethod(tmp119)
	if !this.FilterMethod.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.FilterMethod, this._io, "/types/ihdr_chunk/seq/5")
	}
	tmp120, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.InterlaceMethod = Png_InterlaceMethod(tmp120)
	if !this.InterlaceMethod.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.InterlaceMethod, this._io, "/types/ihdr_chunk/seq/6")
	}
	return err
}
type Png_InternationalText struct {
	Value string
	_io *kaitai.Stream
	_root *Png
	_parent *Png_InternationalTextChunk
}
func NewPng_InternationalText() *Png_InternationalText {
	return &Png_InternationalText{
	}
}

func (this Png_InternationalText) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_InternationalText) Read(io *kaitai.Stream, parent *Png_InternationalTextChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp121, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp121 = tmp121
	this.Value = string(tmp121)
	return err
}

/**
 * Text string (the "value" of this key-value pair), written in language
 * specified in `_parent.language_tag`.
 * 
 * Although it is not null-terminated (unlike other textual data in the
 * `iTXt` chunk), it must not contain a zero byte
 * (U+0000 NULL character). A newline should be represented by a single
 * U+000A LINE FEED (LF) character (aka `\n`). The remaining control
 * characters (U+0001..U+0009, U+000B..0+001F, U+007F..U+009F) are
 * discouraged.
 */

/**
 * International textual data (`iTXt`) chunk effectively allows you to store
 * key-value string pairs in the PNG container.
 * 
 * The "key" part (`keyword`) is restricted to printable ISO-8859-1 (Latin-1)
 * characters and spaces. The translated keyword and the "value" part
 * (`text`) are stored in UTF-8 and thus can store text in any language -
 * this language can be indicated via the language tag (`language_tag`).
 * @see <a href="https://www.w3.org/TR/png/#11iTXt">Source</a>
 */
type Png_InternationalTextChunk struct {
	Keyword string
	CompressionFlag uint8
	CompressionMethod Png_CompressionMethods
	LanguageTag string
	TranslatedKeyword string
	TextPlain *Png_InternationalText
	TextZlib *Png_InternationalText
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_raw_TextPlain []byte
	_raw_TextZlib []byte
	_raw__raw_TextZlib []byte
	_f_text bool
	text string
}
func NewPng_InternationalTextChunk() *Png_InternationalTextChunk {
	return &Png_InternationalTextChunk{
	}
}

func (this Png_InternationalTextChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_InternationalTextChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp122, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	tmp123, err := kaitai.BytesToStr(tmp122, charmap.ISO8859_1.NewDecoder())
	if err != nil {
		return err
	}
	this.Keyword = tmp123
	tmp124, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.CompressionFlag = tmp124
	if !( ((this.CompressionFlag == 0) || (this.CompressionFlag == 1)) ) {
		return kaitai.NewValidationNotAnyOfError(this.CompressionFlag, this._io, "/types/international_text_chunk/seq/1")
	}
	tmp125, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.CompressionMethod = Png_CompressionMethods(tmp125)
	var tmp126 Png_CompressionMethods;
	if (this.CompressionFlag == 1) {
		tmp126 = Png_CompressionMethods__Zlib
	} else {
		tmp126 = this.CompressionMethod
	}
	var tmp127 Png_CompressionMethods;
	if (this.CompressionFlag == 1) {
		tmp127 = Png_CompressionMethods__Zlib
	} else {
		tmp127 = this.CompressionMethod
	}
	if !(this.CompressionMethod == tmp126) {
		return kaitai.NewValidationNotEqualError(tmp127, this.CompressionMethod, this._io, "/types/international_text_chunk/seq/2")
	}
	tmp128, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	this.LanguageTag = string(tmp128)
	tmp129, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	this.TranslatedKeyword = string(tmp129)
	if (this.CompressionFlag == 0) {
		tmp130, err := this._io.ReadBytesFull()
		if err != nil {
			return err
		}
		tmp130 = tmp130
		this._raw_TextPlain = tmp130
		_io__raw_TextPlain := kaitai.NewStream(bytes.NewReader(this._raw_TextPlain))
		tmp131 := NewPng_InternationalText()
		err = tmp131.Read(_io__raw_TextPlain, this, this._root)
		if err != nil {
			return err
		}
		this.TextPlain = tmp131
	}
	if (this.CompressionFlag == 1) {
		tmp132, err := this._io.ReadBytesFull()
		if err != nil {
			return err
		}
		tmp132 = tmp132
		this._raw__raw_TextZlib = tmp132
		tmp133, err := kaitai.ProcessZlib(this._raw__raw_TextZlib)
		if err != nil {
			return err
		}
		this._raw_TextZlib = tmp133
		_io__raw_TextZlib := kaitai.NewStream(bytes.NewReader(this._raw_TextZlib))
		tmp134 := NewPng_InternationalText()
		err = tmp134.Read(_io__raw_TextZlib, this, this._root)
		if err != nil {
			return err
		}
		this.TextZlib = tmp134
	}
	return err
}

/**
 * Text string (the "value" of this key-value pair), written in language
 * specified in `language_tag`.
 * 
 * Although it is not null-terminated (unlike other textual data in the
 * `iTXt` chunk), it must not contain a zero byte
 * (U+0000 NULL character). A newline should be represented by a single
 * U+000A LINE FEED (LF) character (aka `\n`). The remaining control
 * characters (U+0001..U+0009, U+000B..0+001F, U+007F..U+009F) are
 * discouraged.
 */
func (this *Png_InternationalTextChunk) Text() (v string, err error) {
	if (this._f_text) {
		return this.text, nil
	}
	this._f_text = true
	var tmp135 *Png_InternationalText;
	if (this.CompressionFlag == 0) {
		tmp135 = this.TextPlain
	} else {
		tmp135 = this.TextZlib
	}
	this.text = string(tmp135.Value)
	return this.text, nil
}

/**
 * Indicates the type of information represented by the text string.
 * 
 * Keywords must consist exclusively of printable ISO-8859-1 (Latin-1)
 * characters and spaces; that is, only code points 0x20-0x7E and
 * 0xA1-0xFF are allowed. To reduce the chances for human misreading of a
 * keyword, leading spaces, trailing spaces, and consecutive spaces are
 * not permitted.
 * @see <a href="https://www.w3.org/TR/2025/REC-png-3-20250624/#11keywords">Source</a>
 */

/**
 * 0 = text is uncompressed, 1 = text is compressed with a
 * method specified in `compression_method`.
 */

/**
 * Human language used in the `translated_keyword` and `text` fields.
 * 
 * From the [official
 * specification](https://www.w3.org/TR/2025/REC-png-3-20250624/#11iTXt):
 * 
 * > The language tag is a well-formed language tag defined by [RFC 5646:
 * > BCP 47: Tags for Identifying
 * > Languages](https://www.rfc-editor.org/info/rfc5646/). Unlike the
 * > keyword, the language tag is case-insensitive. Subtags must appear
 * > in the [IANA language subtag
 * > registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).
 * > If the language tag is empty, the language is unspecified. Examples
 * > of language tags include: `en`, `en-GB`, `es-419`, `zh-Hans`,
 * > `zh-Hans-CN`, `tlh-Cyrl-AQ`, `ar-AE-u-nu-latn`, and `x-private`.
 */

/**
 * The keyword (`keyword`) translated into the language specified in
 * `language_tag`.
 * 
 * It must not contain a zero byte (U+0000 NULL character). Line breaks
 * should not appear. The remaining control characters (U+0001..U+0009,
 * U+000B..0+001F, U+007F..U+009F) are discouraged.
 */
type Png_MdcvChromaticity struct {
	XInt uint16
	YInt uint16
	_io *kaitai.Stream
	_root *Png
	_parent *Png_MdcvChunk
	_f_x bool
	x float64
	_f_y bool
	y float64
}
func NewPng_MdcvChromaticity() *Png_MdcvChromaticity {
	return &Png_MdcvChromaticity{
	}
}

func (this Png_MdcvChromaticity) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_MdcvChromaticity) Read(io *kaitai.Stream, parent *Png_MdcvChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp136, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.XInt = uint16(tmp136)
	tmp137, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.YInt = uint16(tmp137)
	return err
}
func (this *Png_MdcvChromaticity) X() (v float64, err error) {
	if (this._f_x) {
		return this.x, nil
	}
	this._f_x = true
	this.x = float64(this.XInt * 0.00002)
	return this.x, nil
}
func (this *Png_MdcvChromaticity) Y() (v float64, err error) {
	if (this._f_y) {
		return this.y, nil
	}
	this._f_y = true
	this.y = float64(this.YInt * 0.00002)
	return this.y, nil
}

/**
 * @see <a href="https://www.w3.org/TR/png/#mDCV-chunk">Source</a>
 * @see <a href="https://w3c.github.io/png/Implementation_Report_3e/#mastering">Source</a>
 */
type Png_MdcvChunk struct {
	Red *Png_MdcvChromaticity
	Green *Png_MdcvChromaticity
	Blue *Png_MdcvChromaticity
	WhitePoint *Png_MdcvChromaticity
	MaxLuminanceInt uint32
	MinLuminanceInt uint32
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_f_maxLuminance bool
	maxLuminance float64
	_f_minLuminance bool
	minLuminance float64
}
func NewPng_MdcvChunk() *Png_MdcvChunk {
	return &Png_MdcvChunk{
	}
}

func (this Png_MdcvChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_MdcvChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp138 := NewPng_MdcvChromaticity()
	err = tmp138.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Red = tmp138
	tmp139 := NewPng_MdcvChromaticity()
	err = tmp139.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Green = tmp139
	tmp140 := NewPng_MdcvChromaticity()
	err = tmp140.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Blue = tmp140
	tmp141 := NewPng_MdcvChromaticity()
	err = tmp141.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.WhitePoint = tmp141
	tmp142, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.MaxLuminanceInt = uint32(tmp142)
	tmp143, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.MinLuminanceInt = uint32(tmp143)
	return err
}

/**
 * Maximum luminance in cd/m^2
 */
func (this *Png_MdcvChunk) MaxLuminance() (v float64, err error) {
	if (this._f_maxLuminance) {
		return this.maxLuminance, nil
	}
	this._f_maxLuminance = true
	this.maxLuminance = float64(this.MaxLuminanceInt * 0.0001)
	return this.maxLuminance, nil
}

/**
 * Minimum luminance in cd/m^2
 */
func (this *Png_MdcvChunk) MinLuminance() (v float64, err error) {
	if (this._f_minLuminance) {
		return this.minLuminance, nil
	}
	this._f_minLuminance = true
	this.minLuminance = float64(this.MinLuminanceInt * 0.0001)
	return this.minLuminance, nil
}

/**
 * Physical pixel dimensions (`pHYs`) chunk specifies the intended physical
 * size of the pixels (in meters) or pixel aspect ratio for display of the
 * image.
 * @see <a href="https://www.w3.org/TR/png/#11pHYs">Source</a>
 */
type Png_PhysChunk struct {
	PixelsPerUnitX uint32
	PixelsPerUnitY uint32
	Unit Png_PhysUnit
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
	_f_dotsPerInchX bool
	dotsPerInchX float64
	_f_dotsPerInchY bool
	dotsPerInchY float64
}
func NewPng_PhysChunk() *Png_PhysChunk {
	return &Png_PhysChunk{
	}
}

func (this Png_PhysChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_PhysChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp144, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.PixelsPerUnitX = uint32(tmp144)
	tmp145, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.PixelsPerUnitY = uint32(tmp145)
	tmp146, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unit = Png_PhysUnit(tmp146)
	if !this.Unit.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.Unit, this._io, "/types/phys_chunk/seq/2")
	}
	return err
}

/**
 * Horizontal resolution (DPI)
 */
func (this *Png_PhysChunk) DotsPerInchX() (v float64, err error) {
	if (this._f_dotsPerInchX) {
		return this.dotsPerInchX, nil
	}
	this._f_dotsPerInchX = true
	if (this.Unit == Png_PhysUnit__Meter) {
		this.dotsPerInchX = float64(this.PixelsPerUnitX * 0.0254)
	}
	return this.dotsPerInchX, nil
}

/**
 * Vertical resolution (DPI)
 */
func (this *Png_PhysChunk) DotsPerInchY() (v float64, err error) {
	if (this._f_dotsPerInchY) {
		return this.dotsPerInchY, nil
	}
	this._f_dotsPerInchY = true
	if (this.Unit == Png_PhysUnit__Meter) {
		this.dotsPerInchY = float64(this.PixelsPerUnitY * 0.0254)
	}
	return this.dotsPerInchY, nil
}

/**
 * Number of pixels per physical unit (typically, 1 meter) by X
 * axis.
 */

/**
 * Number of pixels per physical unit (typically, 1 meter) by Y
 * axis.
 */

/**
 * @see <a href="https://www.w3.org/TR/png/#11PLTE">Source</a>
 */
type Png_PlteChunk struct {
	Entries []*Png_Rgb
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_PlteChunk() *Png_PlteChunk {
	return &Png_PlteChunk{
	}
}

func (this Png_PlteChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_PlteChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0;; i++ {
		tmp147, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp147 {
			break
		}
		tmp148 := NewPng_Rgb()
		err = tmp148.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp148)
	}
	return err
}
type Png_Rgb struct {
	R uint8
	G uint8
	B uint8
	_io *kaitai.Stream
	_root *Png
	_parent *Png_PlteChunk
}
func NewPng_Rgb() *Png_Rgb {
	return &Png_Rgb{
	}
}

func (this Png_Rgb) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_Rgb) Read(io *kaitai.Stream, parent *Png_PlteChunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp149, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.R = tmp149
	tmp150, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.G = tmp150
	tmp151, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.B = tmp151
	return err
}

/**
 * @see <a href="https://www.w3.org/TR/png/#11sRGB">Source</a>
 */

type Png_SrgbChunk_Intent int
const (
	Png_SrgbChunk_Intent__Perceptual Png_SrgbChunk_Intent = 0
	Png_SrgbChunk_Intent__RelativeColorimetric Png_SrgbChunk_Intent = 1
	Png_SrgbChunk_Intent__Saturation Png_SrgbChunk_Intent = 2
	Png_SrgbChunk_Intent__AbsoluteColorimetric Png_SrgbChunk_Intent = 3
)
var values_Png_SrgbChunk_Intent = map[Png_SrgbChunk_Intent]struct{}{0: {}, 1: {}, 2: {}, 3: {}}
func (v Png_SrgbChunk_Intent) isDefined() bool {
	_, ok := values_Png_SrgbChunk_Intent[v]
	return ok
}
type Png_SrgbChunk struct {
	RenderIntent Png_SrgbChunk_Intent
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_SrgbChunk() *Png_SrgbChunk {
	return &Png_SrgbChunk{
	}
}

func (this Png_SrgbChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_SrgbChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp152, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.RenderIntent = Png_SrgbChunk_Intent(tmp152)
	if !this.RenderIntent.isDefined() {
		return kaitai.NewValidationNotInEnumError(this.RenderIntent, this._io, "/types/srgb_chunk/seq/0")
	}
	return err
}

/**
 * Textual data (`tEXt`) chunk effectively allows you to store key-value
 * string pairs in the PNG container.
 * 
 * Both the "key" (`keyword`) and "value" (`text`) parts are restricted to
 * printable ISO-8859-1 (Latin-1) characters and ASCII spaces, with the
 * exception that `text` can also contain newlines (U+000A LINE FEED (LF)
 * characters) and U+00A0 NON-BREAKING SPACE characters.
 * @see <a href="https://www.w3.org/TR/png/#11tEXt">Source</a>
 */
type Png_TextChunk struct {
	Keyword string
	Text string
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_TextChunk() *Png_TextChunk {
	return &Png_TextChunk{
	}
}

func (this Png_TextChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_TextChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp153, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	tmp154, err := kaitai.BytesToStr(tmp153, charmap.ISO8859_1.NewDecoder())
	if err != nil {
		return err
	}
	this.Keyword = tmp154
	tmp155, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp155 = tmp155
	tmp156, err := kaitai.BytesToStr(tmp155, charmap.ISO8859_1.NewDecoder())
	if err != nil {
		return err
	}
	this.Text = tmp156
	return err
}

/**
 * Indicates the type of information represented by the text string.
 * 
 * Keywords must consist exclusively of printable ISO-8859-1 (Latin-1)
 * characters and spaces; that is, only code points 0x20-0x7E and
 * 0xA1-0xFF are allowed. To reduce the chances for human misreading of a
 * keyword, leading spaces, trailing spaces, and consecutive spaces are
 * not permitted.
 * @see <a href="https://www.w3.org/TR/2025/REC-png-3-20250624/#11keywords">Source</a>
 */

/**
 * Text string (the "value" of this key-value pair).
 * 
 * Although it is not null-terminated (unlike the keyword), it must not
 * contain a zero byte (U+0000 NULL character). A newline should be
 * represented by a single U+000A LINE FEED (LF) character (aka `\n`).
 * The remaining control characters (U+0001..U+0009, U+000B..0+001F,
 * U+007F..U+009F) are discouraged.
 */

/**
 * Time chunk stores time stamp of last modification of this image,
 * up to 1 second precision in UTC timezone.
 * @see <a href="https://www.w3.org/TR/png/#11tIME">Source</a>
 */
type Png_TimeChunk struct {
	Year uint16
	Month uint8
	Day uint8
	Hour uint8
	Minute uint8
	Second uint8
	_io *kaitai.Stream
	_root *Png
	_parent *Png_Chunk
}
func NewPng_TimeChunk() *Png_TimeChunk {
	return &Png_TimeChunk{
	}
}

func (this Png_TimeChunk) IO_() *kaitai.Stream {
	return this._io
}

func (this *Png_TimeChunk) Read(io *kaitai.Stream, parent *Png_Chunk, root *Png) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp157, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.Year = uint16(tmp157)
	tmp158, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Month = tmp158
	tmp159, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Day = tmp159
	tmp160, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Hour = tmp160
	tmp161, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Minute = tmp161
	tmp162, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Second = tmp162
	return err
}
